### ISSUE TITLE
云平台镜像/虚拟机镜像，百度网盘密码不对

### ISSUE THREAD

**Issue by wuyish** [CoolToneSummer/Competition-Resources-for-Ruijie#1]
打开云平台镜像/虚拟机镜像百度网盘下载，提示密码不对。

**Comment by CoolToneSummer** [comment]
复制粘贴密码 密码是对的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoolToneSummer/Competition-Resources-for-Ruijie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上7:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[CoolToneSummer/Competition-Resources-for-Ruijie] 云平台镜像/虚拟机镜像，百度网盘密码不对 (#1)





 
打开云平台镜像/虚拟机镜像百度网盘下载，提示密码不对。

**Comment by wuyish** [comment]
找到另一个链接复制粘贴密码后能下载了。谢谢
